server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://turntable.proxy.rlwy.net:41048/railway
    username: root
    password: lmFyobXPljjxPxFTvbEDCArdiESMRtvl
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true